name: Node CI

on:
 push:
    branches:
      - master
 pull_request:
    branches:
      - master

jobs:
  upload-designer-codecov:
    runs-on: ubuntu-latest
    # if: ${{ github.event.pull_request.head.repo.full_name == 'alibaba/lowcode-engine' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # working-directory: packages/designer
          files: ./clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
